### ISSUE TITLE
Can you provide any resources about the theory behind high order spectra analysis of time series?

### ISSUE THREAD

**Issue by ahmeddeladly** [trichter/polycoherence#2]
Hello Trichter,

Thanks for your code. I was wondering if you can suggest any intuitive (ideally not too mathematical) references on high order spectra analysis. I am working with time series recorded from the brain. 

Thanks in advance :)

**Comment by trichter** [comment]
Hi,

sorry, I cannot provide a good reference. I only googled my way through the theory. If you find a good reference, please post it here. Thanks.

**Comment by Pandafeng-HHU** [comment]
Hello Trichter,
Thanks for your code. I am a researcher studying heart sound signals, and your code is very useful. But I don't understand the principle behind its implementation. Can you provide me with your reference material? I haven't found any relevant information on converting from spectrogram to bispectrum
