### ISSUE TITLE
Selection of "npreseg" and "noverlap" to run the polycoherence code

### ISSUE THREAD

**Issue by heramb96** [trichter/polycoherence#3]
Hello Trichter,

I am trying to calculate bicoherence for wave interactions.  I use 1024 velocity samples. Could you please let me know how to select the optimum values of nperseg and noverlap in the polycoherence code?

Thanks
Siva

**Comment by trichter** [comment]
Maybe try out different values and check out the plots. Also depends on your sampling rate and the frequency of the signals you expect to couple.
